POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Hola",
  "author": "Chau",
  "url": "https://fullstackopen.com/",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFscGFyZ2F0YS5Db3NtaWNhMiIsImlkIjoiNjg2ZjhkMzlkNDgxYTVmNDlkMDcyY2YyIiwiaWF0IjoxNzUyMTQxNzk1fQ.RHl7DmvXgeOwRsamIx7trASml1WXDawcb-CgOEaBxiE

{
  "title": "How to cook pasta",
  "author": "Don Pastalon",
  "url": "https://pastainthenight.com/",
  "likes": 15013
}
